# Generated by Django 5.1.1 on 2025-10-01 15:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("order_date", models.DateField(auto_now_add=True)),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="RON", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "În așteptare"),
                            ("sent_to_partner", "Trimisă către partener"),
                            ("in_delivery", "În livrare"),
                            ("delivered", "Livrată"),
                            ("cancelled", "Anulată"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("delivery_date", models.DateField()),
                ("sap_sync_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comandă",
                "verbose_name_plural": "Comenzi",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.IntegerField()),
                ("material_code", models.CharField(max_length=100)),
                ("material_description", models.CharField(max_length=255)),
                (
                    "quantity_ordered",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("unit_of_measure", models.CharField(max_length=10)),
                ("delivery_date", models.DateField()),
                ("net_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("price_unit", models.CharField(max_length=10)),
                ("price_unit_order", models.CharField(blank=True, max_length=10)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "quantity_delivered",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poziție comandă",
                "verbose_name_plural": "Poziții comandă",
                "ordering": ["position"],
                "unique_together": {("order", "position")},
            },
        ),
    ]
